# Generated by Django 3.1.7 on 2021-03-25 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='notes_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=list, size=256),
            preserve_default=False,
        ),
    ]
