# Generated by Django 3.1.7 on 2021-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_notes_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
