# Generated by Django 3.1.7 on 2021-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
